meta_product_name: "Clubin"
meta_title: "Clubin - Make the most of your night"
meta_description: "Let's face it waiting sucks. And it sucks even more if the party you waited for is not even lit. But no worries we got you. Clubin shows you based on live data how the queue and the atmosphere of a club are currently. So you can make the most of your night."
meta_image: "meta.png"
